services:
  myapp:
    container_name: myapp-react-native
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8081:8081
# volumes:
#   node_modules:
