name: golang-lint

on:
  pull_request:
    types: [opened, synchronize]  # PRのオープンと更新時のみ実行
  workflow_dispatch:

jobs:
  golangci-lint:
    name: "golangci-lint"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies  # 依存関係の明示的なインストール
        run: |
          cd backend
          go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: backend
